# Generated by Django 4.2.17 on 2024-12-26 22:18

from django.db import migrations
from django.conf import settings

from pckgs.crpt.sync_encryptor import SyncEncryptor


def encrypt_existing_descriptions(apps, schema_editor):
    Note = apps.get_model('core', 'Note')
    encryptor = SyncEncryptor()

    for note in Note.objects.all():
        if note.description:
            encrypted_description, _ = encryptor.encrypt(
                data=note.description,
                passphrase=settings.SECRET_KEY
            )
            note.description = encrypted_description
            note.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file'),
    ]

    operations = [
        migrations.RunPython(
            encrypt_existing_descriptions,
        ),
    ]
